
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Aug 28 15:53:12 CST 2020
//----------------------------------------------------

package ProjectTC.Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 20;
  public static final int Llave_c = 27;
  public static final int Op_booleano = 23;
  public static final int Llave_a = 26;
  public static final int If = 8;
  public static final int Evitar = 34;
  public static final int Void = 3;
  public static final int T_dato = 5;
  public static final int Importe = 40;
  public static final int Else = 9;
  public static final int Corchete_c = 29;
  public static final int Corchete_a = 28;
  public static final int Punto = 46;
  public static final int While = 11;
  public static final int Division = 17;
  public static final int Int = 6;
  public static final int Cadena = 7;
  public static final int Parentesis_c = 25;
  public static final int Parentesis_a = 24;
  public static final int For = 12;
  public static final int Captura_do = 35;
  public static final int EOF = 0;
  public static final int P_coma = 31;
  public static final int error = 1;
  public static final int Texto = 55;
  public static final int Private = 53;
  public static final int Arreglo_Int = 42;
  public static final int Linea = 2;
  public static final int Captura_t = 38;
  public static final int Op_atribucion = 21;
  public static final int Importacion = 44;
  public static final int ERROR = 56;
  public static final int Do = 10;
  public static final int Clase_s = 50;
  public static final int Impresion_p = 43;
  public static final int Op_logico = 19;
  public static final int Public = 49;
  public static final int Clase_p = 48;
  public static final int Matriz_s = 45;
  public static final int Dos_puntos = 39;
  public static final int New = 41;
  public static final int Identificador = 32;
  public static final int Mod = 18;
  public static final int paquete = 47;
  public static final int Arreglo_Float = 36;
  public static final int Resta = 15;
  public static final int Matriz_e = 37;
  public static final int Matriz_c = 51;
  public static final int Multiplicacion = 16;
  public static final int Arreglo_String = 54;
  public static final int Op_incremento = 22;
  public static final int Numero = 33;
  public static final int Suma = 14;
  public static final int Main = 30;
  public static final int Igual = 13;
  public static final int casos = 52;
  public static final int Comillas = 4;
}

