/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectTC;

import ProjectTC.Ayuda.Helper;
import ProjectTC.Ayuda.lector_pdf;
import ProjectTC.Analizador.Panel_Lexico;
import ProjectTC.Analizador.Panel_Sintactico;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JPanel;

/**
 *
 * @author joshg
 */
public class MainMenu extends javax.swing.JFrame {
    private static Panel_Lexico Lexico;
    private static Panel_Sintactico Sintactico;
    private int PrincipalChanged = -1;
    Helper VerAyuda;
    Rectangle abounds;
    Dimension dim; 
    /**
     * Creates new form NewJFrame
     */
    public MainMenu() {
        initComponents();
        dim = getToolkit().getScreenSize();
        abounds = this.getBounds();
        Panel_Ayuda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lbTitulo = new javax.swing.JLabel();
        Panel = new keeptoo.KGradientPanel();
        Panel_Slider = new rojerusan.RSPanelsSlider();
        btn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        btnLexico = new javax.swing.JButton();
        btn_2 = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        btnSintactico = new javax.swing.JButton();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        BotónRecursión1 = new javax.swing.JButton();
        Panel_Ayuda = new javax.swing.JPanel();
        btn_1_1 = new javax.swing.JPanel();
        ind_1_1 = new javax.swing.JPanel();
        btnHlexico = new javax.swing.JButton();
        btn_1_2 = new javax.swing.JPanel();
        ind_1_2 = new javax.swing.JPanel();
        btnHSintatico = new javax.swing.JButton();
        btn_1_3 = new javax.swing.JPanel();
        ind_1_3 = new javax.swing.JPanel();
        btnIfse = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btn_1_4 = new javax.swing.JPanel();
        ind_1_4 = new javax.swing.JPanel();
        btnFor = new javax.swing.JButton();
        btn_1_5 = new javax.swing.JPanel();
        ind_1_5 = new javax.swing.JPanel();
        btnWhile = new javax.swing.JButton();
        btn_1_6 = new javax.swing.JPanel();
        ind_1_6 = new javax.swing.JPanel();
        btnDowhile = new javax.swing.JButton();
        btn_1_7 = new javax.swing.JPanel();
        ind_1_7 = new javax.swing.JPanel();
        btnSwitch = new javax.swing.JButton();
        MainPanel = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMenú = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnClose = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 660));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1110, 660));

        kGradientPanel1.setkEndColor(new java.awt.Color(123, 156, 225));
        kGradientPanel1.setkStartColor(new java.awt.Color(123, 156, 225));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1110, 660));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Menú Principal");

        Panel.setkEndColor(new java.awt.Color(71, 120, 197));
        Panel.setkStartColor(new java.awt.Color(71, 120, 197));
        Panel.setMinimumSize(new java.awt.Dimension(880, 418));

        Panel_Slider.setBackground(new java.awt.Color(23, 35, 51));
        Panel_Slider.setMinimumSize(new java.awt.Dimension(224, 614));
        Panel_Slider.setPreferredSize(new java.awt.Dimension(224, 627));

        btn_1.setBackground(new java.awt.Color(23, 35, 51));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        ind_1.setBackground(new java.awt.Color(255, 255, 255));
        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnLexico.setBackground(new java.awt.Color(169, 224, 49));
        btnLexico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLexico.setForeground(new java.awt.Color(255, 255, 255));
        btnLexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-letra-pequeña-24.png"))); // NOI18N
        btnLexico.setText("Lexico ");
        btnLexico.setToolTipText("Analizador Lexico");
        btnLexico.setBorder(null);
        btnLexico.setBorderPainted(false);
        btnLexico.setContentAreaFilled(false);
        btnLexico.setFocusPainted(false);
        btnLexico.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLexico.setRequestFocusEnabled(false);
        btnLexico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-letra-pequeña-24 (1).png"))); // NOI18N
        btnLexico.setVerifyInputWhenFocusTarget(false);
        btnLexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLexicoMouseClicked(evt);
            }
        });
        btnLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ind_1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btnLexico, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_2.setBackground(new java.awt.Color(23, 35, 51));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_2MousePressed(evt);
            }
        });

        ind_2.setBackground(new java.awt.Color(255, 255, 255));
        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnSintactico.setBackground(new java.awt.Color(169, 224, 49));
        btnSintactico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSintactico.setForeground(new java.awt.Color(255, 255, 255));
        btnSintactico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-java-24 (1).png"))); // NOI18N
        btnSintactico.setText("Sintáctico");
        btnSintactico.setToolTipText("Analizador Sintáctico");
        btnSintactico.setBorder(null);
        btnSintactico.setBorderPainted(false);
        btnSintactico.setContentAreaFilled(false);
        btnSintactico.setFocusPainted(false);
        btnSintactico.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSintactico.setRequestFocusEnabled(false);
        btnSintactico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-java-24.png"))); // NOI18N
        btnSintactico.setVerifyInputWhenFocusTarget(false);
        btnSintactico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSintacticoMouseClicked(evt);
            }
        });
        btnSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSintacticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addComponent(btnSintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(ind_2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        btn_3.setBackground(new java.awt.Color(23, 35, 51));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind_3.setBackground(new java.awt.Color(255, 255, 255));
        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BotónRecursión1.setBackground(new java.awt.Color(169, 224, 49));
        BotónRecursión1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotónRecursión1.setForeground(new java.awt.Color(255, 255, 255));
        BotónRecursión1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-ayuda-24.png"))); // NOI18N
        BotónRecursión1.setText("Ayuda");
        BotónRecursión1.setToolTipText("Ayuda");
        BotónRecursión1.setBorder(null);
        BotónRecursión1.setBorderPainted(false);
        BotónRecursión1.setContentAreaFilled(false);
        BotónRecursión1.setFocusPainted(false);
        BotónRecursión1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BotónRecursión1.setRequestFocusEnabled(false);
        BotónRecursión1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-ayuda-24 (1).png"))); // NOI18N
        BotónRecursión1.setVerifyInputWhenFocusTarget(false);
        BotónRecursión1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónRecursión1MouseClicked(evt);
            }
        });
        BotónRecursión1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónRecursión1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotónRecursión1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(BotónRecursión1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(ind_3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        Panel_Ayuda.setBackground(new java.awt.Color(23, 35, 51));

        btn_1_1.setBackground(new java.awt.Color(23, 35, 51));
        btn_1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1_1MousePressed(evt);
            }
        });

        ind_1_1.setOpaque(false);
        ind_1_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1_1Layout = new javax.swing.GroupLayout(ind_1_1);
        ind_1_1.setLayout(ind_1_1Layout);
        ind_1_1Layout.setHorizontalGroup(
            ind_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1_1Layout.setVerticalGroup(
            ind_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btnHlexico.setBackground(new java.awt.Color(169, 224, 49));
        btnHlexico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHlexico.setForeground(new java.awt.Color(255, 255, 255));
        btnHlexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-development-skill-24.png"))); // NOI18N
        btnHlexico.setText("Lexico");
        btnHlexico.setToolTipText("Analizador Lexico");
        btnHlexico.setBorder(null);
        btnHlexico.setBorderPainted(false);
        btnHlexico.setContentAreaFilled(false);
        btnHlexico.setFocusPainted(false);
        btnHlexico.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHlexico.setRequestFocusEnabled(false);
        btnHlexico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-development-skill-24 (1).png"))); // NOI18N
        btnHlexico.setVerifyInputWhenFocusTarget(false);
        btnHlexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHlexicoMouseClicked(evt);
            }
        });
        btnHlexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHlexicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1_1Layout = new javax.swing.GroupLayout(btn_1_1);
        btn_1_1.setLayout(btn_1_1Layout);
        btn_1_1Layout.setHorizontalGroup(
            btn_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1_1Layout.createSequentialGroup()
                .addComponent(ind_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHlexico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_1_1Layout.setVerticalGroup(
            btn_1_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1_1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ind_1_1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addComponent(btnHlexico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_1_2.setBackground(new java.awt.Color(23, 35, 51));
        btn_1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1_2MousePressed(evt);
            }
        });

        ind_1_2.setOpaque(false);
        ind_1_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1_2Layout = new javax.swing.GroupLayout(ind_1_2);
        ind_1_2.setLayout(ind_1_2Layout);
        ind_1_2Layout.setHorizontalGroup(
            ind_1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1_2Layout.setVerticalGroup(
            ind_1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btnHSintatico.setBackground(new java.awt.Color(169, 224, 49));
        btnHSintatico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHSintatico.setForeground(new java.awt.Color(255, 255, 255));
        btnHSintatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-multichannel-24.png"))); // NOI18N
        btnHSintatico.setText("Sintáctico");
        btnHSintatico.setToolTipText("Analizador Sintáctico");
        btnHSintatico.setBorder(null);
        btnHSintatico.setBorderPainted(false);
        btnHSintatico.setContentAreaFilled(false);
        btnHSintatico.setFocusPainted(false);
        btnHSintatico.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHSintatico.setRequestFocusEnabled(false);
        btnHSintatico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-multichannel-24 (1).png"))); // NOI18N
        btnHSintatico.setVerifyInputWhenFocusTarget(false);
        btnHSintatico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHSintaticoMouseClicked(evt);
            }
        });
        btnHSintatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHSintaticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1_2Layout = new javax.swing.GroupLayout(btn_1_2);
        btn_1_2.setLayout(btn_1_2Layout);
        btn_1_2Layout.setHorizontalGroup(
            btn_1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1_2Layout.createSequentialGroup()
                .addComponent(ind_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHSintatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_1_2Layout.setVerticalGroup(
            btn_1_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1_2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ind_1_2, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addComponent(btnHSintatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_1_3.setBackground(new java.awt.Color(23, 35, 51));
        btn_1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1_3MousePressed(evt);
            }
        });

        ind_1_3.setOpaque(false);
        ind_1_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1_3Layout = new javax.swing.GroupLayout(ind_1_3);
        ind_1_3.setLayout(ind_1_3Layout);
        ind_1_3Layout.setHorizontalGroup(
            ind_1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1_3Layout.setVerticalGroup(
            ind_1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btnIfse.setBackground(new java.awt.Color(169, 224, 49));
        btnIfse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIfse.setForeground(new java.awt.Color(255, 255, 255));
        btnIfse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-train-track-24.png"))); // NOI18N
        btnIfse.setText("IF- Else");
        btnIfse.setToolTipText("Condicionales IF- Else");
        btnIfse.setBorder(null);
        btnIfse.setBorderPainted(false);
        btnIfse.setContentAreaFilled(false);
        btnIfse.setFocusPainted(false);
        btnIfse.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnIfse.setRequestFocusEnabled(false);
        btnIfse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-train-track-24 (1).png"))); // NOI18N
        btnIfse.setVerifyInputWhenFocusTarget(false);
        btnIfse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIfseMouseClicked(evt);
            }
        });
        btnIfse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIfseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1_3Layout = new javax.swing.GroupLayout(btn_1_3);
        btn_1_3.setLayout(btn_1_3Layout);
        btn_1_3Layout.setHorizontalGroup(
            btn_1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1_3Layout.createSequentialGroup()
                .addComponent(ind_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIfse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_1_3Layout.setVerticalGroup(
            btn_1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1_3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ind_1_3, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addComponent(btnIfse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator3.setBackground(new java.awt.Color(23, 35, 51));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(23, 35, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Analizador");

        jLabel2.setBackground(new java.awt.Color(23, 35, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estructura de Java");

        jSeparator4.setBackground(new java.awt.Color(23, 35, 51));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        btn_1_4.setBackground(new java.awt.Color(23, 35, 51));
        btn_1_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1_4MousePressed(evt);
            }
        });

        ind_1_4.setOpaque(false);
        ind_1_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1_4Layout = new javax.swing.GroupLayout(ind_1_4);
        ind_1_4.setLayout(ind_1_4Layout);
        ind_1_4Layout.setHorizontalGroup(
            ind_1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1_4Layout.setVerticalGroup(
            ind_1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btnFor.setBackground(new java.awt.Color(169, 224, 49));
        btnFor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFor.setForeground(new java.awt.Color(255, 255, 255));
        btnFor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-roller-coaster-24.png"))); // NOI18N
        btnFor.setText("For");
        btnFor.setToolTipText("Sentencia For");
        btnFor.setBorder(null);
        btnFor.setBorderPainted(false);
        btnFor.setContentAreaFilled(false);
        btnFor.setFocusPainted(false);
        btnFor.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnFor.setRequestFocusEnabled(false);
        btnFor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-roller-coaster-24 (1).png"))); // NOI18N
        btnFor.setVerifyInputWhenFocusTarget(false);
        btnFor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnForMouseClicked(evt);
            }
        });
        btnFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1_4Layout = new javax.swing.GroupLayout(btn_1_4);
        btn_1_4.setLayout(btn_1_4Layout);
        btn_1_4Layout.setHorizontalGroup(
            btn_1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1_4Layout.createSequentialGroup()
                .addComponent(ind_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_1_4Layout.setVerticalGroup(
            btn_1_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1_4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ind_1_4, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addComponent(btnFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_1_5.setBackground(new java.awt.Color(23, 35, 51));
        btn_1_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1_5MousePressed(evt);
            }
        });

        ind_1_5.setOpaque(false);
        ind_1_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1_5Layout = new javax.swing.GroupLayout(ind_1_5);
        ind_1_5.setLayout(ind_1_5Layout);
        ind_1_5Layout.setHorizontalGroup(
            ind_1_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1_5Layout.setVerticalGroup(
            ind_1_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btnWhile.setBackground(new java.awt.Color(169, 224, 49));
        btnWhile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWhile.setForeground(new java.awt.Color(255, 255, 255));
        btnWhile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-infinity-24 (1).png"))); // NOI18N
        btnWhile.setText("While");
        btnWhile.setToolTipText("Recursión Factorial");
        btnWhile.setBorder(null);
        btnWhile.setBorderPainted(false);
        btnWhile.setContentAreaFilled(false);
        btnWhile.setFocusPainted(false);
        btnWhile.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnWhile.setRequestFocusEnabled(false);
        btnWhile.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-infinity-24.png"))); // NOI18N
        btnWhile.setVerifyInputWhenFocusTarget(false);
        btnWhile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWhileMouseClicked(evt);
            }
        });
        btnWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1_5Layout = new javax.swing.GroupLayout(btn_1_5);
        btn_1_5.setLayout(btn_1_5Layout);
        btn_1_5Layout.setHorizontalGroup(
            btn_1_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1_5Layout.createSequentialGroup()
                .addComponent(ind_1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnWhile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_1_5Layout.setVerticalGroup(
            btn_1_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1_5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ind_1_5, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addComponent(btnWhile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_1_6.setBackground(new java.awt.Color(23, 35, 51));
        btn_1_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1_6MousePressed(evt);
            }
        });

        ind_1_6.setOpaque(false);
        ind_1_6.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1_6Layout = new javax.swing.GroupLayout(ind_1_6);
        ind_1_6.setLayout(ind_1_6Layout);
        ind_1_6Layout.setHorizontalGroup(
            ind_1_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1_6Layout.setVerticalGroup(
            ind_1_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btnDowhile.setBackground(new java.awt.Color(169, 224, 49));
        btnDowhile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDowhile.setForeground(new java.awt.Color(255, 255, 255));
        btnDowhile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-scout-knot-24 (1).png"))); // NOI18N
        btnDowhile.setText("Do - While");
        btnDowhile.setToolTipText("Recursión Factorial");
        btnDowhile.setBorder(null);
        btnDowhile.setBorderPainted(false);
        btnDowhile.setContentAreaFilled(false);
        btnDowhile.setFocusPainted(false);
        btnDowhile.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDowhile.setRequestFocusEnabled(false);
        btnDowhile.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-scout-knot-24.png"))); // NOI18N
        btnDowhile.setVerifyInputWhenFocusTarget(false);
        btnDowhile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDowhileMouseClicked(evt);
            }
        });
        btnDowhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDowhileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1_6Layout = new javax.swing.GroupLayout(btn_1_6);
        btn_1_6.setLayout(btn_1_6Layout);
        btn_1_6Layout.setHorizontalGroup(
            btn_1_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1_6Layout.createSequentialGroup()
                .addComponent(ind_1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDowhile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_1_6Layout.setVerticalGroup(
            btn_1_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1_6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ind_1_6, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addComponent(btnDowhile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_1_7.setBackground(new java.awt.Color(23, 35, 51));
        btn_1_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1_7MousePressed(evt);
            }
        });

        ind_1_7.setOpaque(false);
        ind_1_7.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1_7Layout = new javax.swing.GroupLayout(ind_1_7);
        ind_1_7.setLayout(ind_1_7Layout);
        ind_1_7Layout.setHorizontalGroup(
            ind_1_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1_7Layout.setVerticalGroup(
            ind_1_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        btnSwitch.setBackground(new java.awt.Color(169, 224, 49));
        btnSwitch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSwitch.setForeground(new java.awt.Color(255, 255, 255));
        btnSwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-swiss-army-knife-24.png"))); // NOI18N
        btnSwitch.setText("Switch - Case");
        btnSwitch.setToolTipText("Recursión Factorial");
        btnSwitch.setBorder(null);
        btnSwitch.setBorderPainted(false);
        btnSwitch.setContentAreaFilled(false);
        btnSwitch.setFocusPainted(false);
        btnSwitch.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSwitch.setRequestFocusEnabled(false);
        btnSwitch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-swiss-army-knife-24 (1).png"))); // NOI18N
        btnSwitch.setVerifyInputWhenFocusTarget(false);
        btnSwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSwitchMouseClicked(evt);
            }
        });
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btn_1_7Layout = new javax.swing.GroupLayout(btn_1_7);
        btn_1_7.setLayout(btn_1_7Layout);
        btn_1_7Layout.setHorizontalGroup(
            btn_1_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1_7Layout.createSequentialGroup()
                .addComponent(ind_1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        );
        btn_1_7Layout.setVerticalGroup(
            btn_1_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1_7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ind_1_7, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addComponent(btnSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_AyudaLayout = new javax.swing.GroupLayout(Panel_Ayuda);
        Panel_Ayuda.setLayout(Panel_AyudaLayout);
        Panel_AyudaLayout.setHorizontalGroup(
            Panel_AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_1_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_1_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_1_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_1_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_1_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_1_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4))
                .addContainerGap())
        );
        Panel_AyudaLayout.setVerticalGroup(
            Panel_AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AyudaLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_SliderLayout = new javax.swing.GroupLayout(Panel_Slider);
        Panel_Slider.setLayout(Panel_SliderLayout);
        Panel_SliderLayout.setHorizontalGroup(
            Panel_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_SliderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_SliderLayout.setVerticalGroup(
            Panel_SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SliderLayout.createSequentialGroup()
                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        MainPanel.setkEndColor(new java.awt.Color(71, 120, 197));
        MainPanel.setkStartColor(new java.awt.Color(71, 120, 197));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/grap.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ANALIZADOR LEXICO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Teoria de La Computación");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(Panel_Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Slider, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnMenú.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenú.setForeground(new java.awt.Color(255, 255, 255));
        btnMenú.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-menú-24 (1).png"))); // NOI18N
        btnMenú.setToolTipText("Menú");
        btnMenú.setBorder(null);
        btnMenú.setBorderPainted(false);
        btnMenú.setContentAreaFilled(false);
        btnMenú.setFocusPainted(false);
        btnMenú.setHideActionText(true);
        btnMenú.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenú.setIconTextGap(20);
        btnMenú.setRequestFocusEnabled(false);
        btnMenú.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-menú-24.png"))); // NOI18N
        btnMenú.setVerifyInputWhenFocusTarget(false);
        btnMenú.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenúMouseClicked(evt);
            }
        });
        btnMenú.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenúActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cerrar-ventana-24 (1).png"))); // NOI18N
        btnClose.setToolTipText("Cerrar");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setFocusPainted(false);
        btnClose.setHideActionText(true);
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClose.setIconTextGap(20);
        btnClose.setRequestFocusEnabled(false);
        btnClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cerrar-ventana-24.png"))); // NOI18N
        btnClose.setVerifyInputWhenFocusTarget(false);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMinimize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-minimize-window-24.png"))); // NOI18N
        btnMinimize.setToolTipText("Minimizar");
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setFocusPainted(false);
        btnMinimize.setHideActionText(true);
        btnMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMinimize.setIconTextGap(20);
        btnMinimize.setRequestFocusEnabled(false);
        btnMinimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-minimize-window-24 (2).png"))); // NOI18N
        btnMinimize.setVerifyInputWhenFocusTarget(false);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenú, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenú, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLexicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLexicoMouseClicked

    private void btnLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexicoActionPerformed
        Lexico  = new Panel_Lexico();
        PrincipalChanged = 0;
        AjustarPanel(Lexico);
        setColor(btn_1);
        ind_1.setOpaque(true);
        lbTitulo.setText("ANALIZADOR LEXICO");
    }//GEN-LAST:event_btnLexicoActionPerformed

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1MousePressed

    private void btnSintacticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSintacticoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSintacticoMouseClicked

    private void btnSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSintacticoActionPerformed
        Sintactico = new Panel_Sintactico(this);
        PrincipalChanged = 1;
        AjustarPanel(Sintactico);
        setColor(btn_2);
        ind_2.setOpaque(true);
        lbTitulo.setText("ANALIZADOR SINTATICO");
    }//GEN-LAST:event_btnSintacticoActionPerformed

    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_2MousePressed

    private void BotónRecursión1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónRecursión1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotónRecursión1MouseClicked

    private void BotónRecursión1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónRecursión1ActionPerformed
        AjustarPanel();
        setColor(btn_3);
        ind_3.setOpaque(true);
        Panel_Ayuda.setVisible(true);
    }//GEN-LAST:event_BotónRecursión1ActionPerformed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_3MousePressed

    private void btnHlexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHlexicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHlexicoMouseClicked

    private void btnHlexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHlexicoActionPerformed
        showHelper(1);
    }//GEN-LAST:event_btnHlexicoActionPerformed

    private void btn_1_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1_1MousePressed

    private void btnHSintaticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHSintaticoMouseClicked

    }//GEN-LAST:event_btnHSintaticoMouseClicked

    private void btnHSintaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHSintaticoActionPerformed
        showHelper(2);
    }//GEN-LAST:event_btnHSintaticoActionPerformed

    private void btn_1_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1_2MousePressed

    private void btnIfseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIfseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIfseMouseClicked

    private void btnIfseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIfseActionPerformed
        showHelper(3);
    }//GEN-LAST:event_btnIfseActionPerformed

    private void btn_1_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1_3MousePressed

    private void btnForMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnForMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnForMouseClicked

    private void btnForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForActionPerformed
        showHelper(4);
    }//GEN-LAST:event_btnForActionPerformed

    private void btn_1_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1_4MousePressed

    private void btnWhileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWhileMouseClicked
        showHelper(5);
    }//GEN-LAST:event_btnWhileMouseClicked

    private void btnWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWhileActionPerformed

    private void btn_1_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1_5MousePressed

    private void btnDowhileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDowhileMouseClicked
        showHelper(6);
    }//GEN-LAST:event_btnDowhileMouseClicked

    private void btnDowhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDowhileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDowhileActionPerformed

    private void btn_1_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1_6MousePressed

    private void btnSwitchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSwitchMouseClicked
        showHelper(7);
    }//GEN-LAST:event_btnSwitchMouseClicked

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSwitchActionPerformed

    private void btn_1_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1_7MousePressed

    private void btnMenúMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenúMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenúMouseClicked

    private void btnMenúActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenúActionPerformed
        //System.out.println(lbTitulo.getBounds());
        if(Panel_Slider.getX() > -1){
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, Panel_Slider);
            MainPanel.setBounds(0, 0, 1110, 619);
            lbTitulo.setBounds(0, 8, 1110, 32);
            
            switch (PrincipalChanged) {
                case -1: 
                    jLabel4.setSize(1110, jLabel4.getHeight());
                    jLabel5.setSize(1110, jLabel5.getHeight());
                    jLabel9.setSize(1110, jLabel9.getHeight());
                    break;
                case 0: Lexico.RedimFull(true); break;
                case 1: Sintactico.RedimFull(true); break;
            }
        }else{
            switch (PrincipalChanged) {
                case -1: 
                    jLabel4.setSize(880, jLabel4.getHeight());
                    jLabel5.setSize(880, jLabel5.getHeight());
                    jLabel9.setSize(880, jLabel9.getHeight());
                    break;
                case 0: Lexico.RedimFull(false); break;
                case 1: Sintactico.RedimFull(true); break;
            }    
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, Panel_Slider);
            MainPanel.setBounds(230, 0, 880, 619);
            lbTitulo.setBounds(208, 8, 880, 32);
        }
    }//GEN-LAST:event_btnMenúActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void AjustarPanel()
    {
        resetColor(new JPanel[]{btn_1,btn_2,btn_3},
                new JPanel[]{ind_1,ind_2,ind_3});
    }
    
    private void AjustarPanel(JPanel PANEL)
    {
        Panel_Ayuda.setVisible(false);
        PANEL.setSize(880, 618);
        PANEL.setLocation(0, 0);
        resetColor(new JPanel[]{btn_1,btn_2,btn_3},
                new JPanel[]{ind_1,ind_2,ind_3});
        MainPanel.removeAll();
        MainPanel.add(PANEL,BorderLayout.CENTER);
        MainPanel.revalidate();
        MainPanel.repaint();
    }
    
     private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for (JPanel pane1 : pane) {
            pane1.setBackground(new Color(23,35,51));
        }
        for (JPanel indicator : indicators) {
            indicator.setOpaque(false);           
        }
        
    }
    
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }

    private void showHelper(int num){
        VerAyuda = new Helper(this,false,num);
        VerAyuda.setLocation(((dim.width - abounds.width) / 2)-85,
            ((dim.height - abounds.height) / 2)-20);
        VerAyuda.setVisible(true);

        this.setLocation(((dim.width - abounds.width) / 2)+90,
            ((dim.height - abounds.height) / 2)-20);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotónRecursión1;
    private keeptoo.KGradientPanel MainPanel;
    private keeptoo.KGradientPanel Panel;
    private javax.swing.JPanel Panel_Ayuda;
    private rojerusan.RSPanelsSlider Panel_Slider;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDowhile;
    private javax.swing.JButton btnFor;
    private javax.swing.JButton btnHSintatico;
    private javax.swing.JButton btnHlexico;
    private javax.swing.JButton btnIfse;
    private javax.swing.JButton btnLexico;
    private javax.swing.JButton btnMenú;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnSintactico;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JButton btnWhile;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_1_1;
    private javax.swing.JPanel btn_1_2;
    private javax.swing.JPanel btn_1_3;
    private javax.swing.JPanel btn_1_4;
    private javax.swing.JPanel btn_1_5;
    private javax.swing.JPanel btn_1_6;
    private javax.swing.JPanel btn_1_7;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_1_1;
    private javax.swing.JPanel ind_1_2;
    private javax.swing.JPanel ind_1_3;
    private javax.swing.JPanel ind_1_4;
    private javax.swing.JPanel ind_1_5;
    private javax.swing.JPanel ind_1_6;
    private javax.swing.JPanel ind_1_7;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
