/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectTC.Ayuda;

import ProjectTC.MainClass;
import VisorPDF.ArchivosVO;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JPanel;
import VisorPDF.MiVisorPDF;

/**
 *
 * @author Jess2
 */
public class Helper extends javax.swing.JDialog {
    private int numImg;

    //Contiene el archivo PDF en bytes de imagenes
    private ArrayList<ArchivosVO> ListaComponente;
    MiVisorPDF pn = new MiVisorPDF();
    ArchivosVO pl = new ArchivosVO();

    //Para mostrar el total de paginas
    private int paginas = -1;
    private int totalp = -1;

    //Guardamos la ruta del PDF--------------------------------------
    private String ruta_archivo = "";
    //---------------------------------------------------------------

    //Mantiene el zoom en la pagina que asignamos
    int zoom = 0;
    Frame Padre;
    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     * @param Num
     */
    
    public Helper(java.awt.Frame parent, boolean modal, int Num) {
        super(parent, modal);
        MainClass MC = new MainClass();
        initComponents();
        Padre = parent;
        
        switch (Num) {
            case 1: 
                lbTitulo.setText("Analizador Lexico (Ayuda)");
                AjustarPanel(MC.getLexPDF());
                break;
            case 2:
                lbTitulo.setText("Analizador Sintáctico (Ayuda)");
                AjustarPanel(MC.getSintPDF());
                break;
            case 3:
                lbTitulo.setText("Estructura If-Else");
                AjustarPanel(new lector_pdf("src/Resources/Sentencia_If.pdf"));
                break;
            case 4:
                lbTitulo.setText("Estructura For");
                AjustarPanel(new lector_pdf("src/Resources/Sentencia_For.pdf"));
                break;
            case 5:
                lbTitulo.setText("Estructura While");
                AjustarPanel(new lector_pdf("src/Resources/Sentencia_While.pdf"));
                break;
            case 6:
                lbTitulo.setText("Estructura Do-While");
                AjustarPanel(new lector_pdf("src/Resources/Sentencia_Do.pdf"));
                break;
            case 7:
                lbTitulo.setText("Estructura Switch-Case");
                AjustarPanel(new lector_pdf("src/Resources/Sentencia_Switch.pdf"));
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lbTitulo = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        btnMenú1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkEndColor(new java.awt.Color(123, 156, 225));
        kGradientPanel1.setkStartColor(new java.awt.Color(123, 156, 225));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Ayuda");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        btnMenú1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenú1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenú1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cerrar-ventana-24 (1).png"))); // NOI18N
        btnMenú1.setToolTipText("Menú");
        btnMenú1.setBorder(null);
        btnMenú1.setBorderPainted(false);
        btnMenú1.setContentAreaFilled(false);
        btnMenú1.setFocusPainted(false);
        btnMenú1.setHideActionText(true);
        btnMenú1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMenú1.setIconTextGap(20);
        btnMenú1.setRequestFocusEnabled(false);
        btnMenú1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cerrar-ventana-24.png"))); // NOI18N
        btnMenú1.setVerifyInputWhenFocusTarget(false);
        btnMenú1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenú1MouseClicked(evt);
            }
        });
        btnMenú1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenú1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenú1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenú1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenú1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenú1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenú1MouseClicked

    private void btnMenú1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenú1ActionPerformed
        dispose();
        Padre.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMenú1ActionPerformed
    
  
    
    private void AjustarPanel(JPanel PANEL)
    {
        PANEL.setSize(400, 619);
        PANEL.setLocation(0, 0);
        MainPanel.removeAll();
        MainPanel.add(PANEL,BorderLayout.CENTER);
        MainPanel.revalidate();
        MainPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnMenú1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
